version: '3.5'

services:      
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: mydb
      POSTGRES_DB: modeling_xp_db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
