# Generated by Django 5.2.7 on 2025-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_clientprofile_agencymodel_talentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=32),
        ),
    ]
