# Generated by Django 5.2.7 on 2025-11-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_entitymodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='entity',
        ),
    ]
